Update snyk_scan.yml

diff --git a/.github/workflows/snyk_scan.yml b/.github/workflows/snyk_scan.yml
--- a/.github/workflows/snyk_scan.yml
+++ b/.github/workflows/snyk_scan.yml
@@ -15,3 +15,15 @@ jobs:
           args: --severity-threshold=high --sarif-file-output=snyk.sarif
       - name: Print the snyk sarif file
         run : cat snyk.sarif
+      - name : Total security issues
+        run : |
+          length=$(cat snyk.sarif | jq '.runs[0].results | length')
+          echo "RESULTS_LENGTH=$length" >> $GITHUB_ENV
+      - name: Pass_or_Fail_the_job
+        run: |
+          if [ "$RESULTS_LENGTH" != 0 ]; then
+            echo "Job Failed"
+            exit 1
+          else
+            echo "Pass"
+          fi
